### ISSUE TITLE
Unpin aiobotocore

### ISSUE THREAD

**Issue by claytonparnell** [conda-forge/amazon-sagemaker-jupyter-scheduler-feedstock#10]
### Comment:

Currently any package that consumes amazon-sagemaker-jupyter-scheduler will be forced to use stale boto3 version due to pinning of aiobotocore. Please unpin this package so that we can update boto3/botocore to newer versions.

**Comment by just4brown** [comment]
To clarify the staleness problem:
* amazon-sagemaker-jupyter-scheduler is currently pinned to aiobotocore 2.7.*
* aiobotocore at 2.7.* enforces the following constraint: [botocore >=1.31.16,<1.31.65](https://github.com/conda-forge/aiobotocore-feedstock/commit/a1f36192660867492a9245927395e2e21ff66fb6) which prevents any closure that consumes this from upgrading boto3 beyond 1.28.64
